### PR TITLE
CO-3395 Sendgrid statuses are considered instead of mail notifications

### PR DESCRIPTION
**Pull request by Theyiot**
Since migration in V12, a new envelop icon has been added to indicate a mail sending that failed. This icon is linked to mail notifications in base _Odoo_ (module _mail_) but for `sendgrid`, the statuses sent by the library aforementioned should be used instead. This is exactly what this _PR_ proposes. Quite a few modifications were required as the module _social_ mostly inherits directly from the _mail_ one. The modifications were all done in this module using inheritance and overriding some fields to obtain the expected behaviour. When a mail could not be sent to some user, only resending the message to those who failed is proposed. This will prevent sending the same message to the same user multiple times.

### CODE REVIEW

**Review by ecino — CHANGES_REQUESTED** [review]
I think that all the changes you made in `mail_tracking` module should be moved inside `mail_sendgrid`. `mail_tracking` module could be used with other mail providers and we don't want to change the behaviour that OCA created there. We only want to change for sendgrid.

**Comment by ecino** [comment]
@Theyiot Can you check this? Maybe it's just that you put "Sendgrid" in the comments that bugs me (you shouldn't mention it outside from the module), but maybe the code can be moved if it's really a specificity regarding sendgrid.

**Comment by Theyiot** [comment]
> @Theyiot Can you check this? Maybe it's just that you put "Sendgrid" in the comments that bugs me (you shouldn't mention it outside from the module), but maybe the code can be moved if it's really a specificity regarding sendgrid.

You are right, I am taking care of the modifications right now.

**Comment by Theyiot** [comment]
@ecino I just pushed the required modifications.

**Review by ecino — APPROVED** [review]

**Pull request merged**
